modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="buildersdelight"
version="0.9"
displayName="Builder's Delight"
logoFile="logo.png"
credits=""
authors="Tynoxs"
description="A mod that aims to add some more variety to minecraft by adding new blocks & items, and also trying to keep the vanilla feeling."

[[dependencies.buildersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.buildersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
